Create کتاب‌های داستانی.md
Amcsui/wiki pull request #9
Opened 2024-09-17 18:58 UTC by HosnaSltn

2024-09-17 19:03 UTC, AminMasoudi requested changes

2024-09-17 19:03 UTC, AminMasoudi commented on docs/کلاب‌ها/بوک کلاب/کتاب‌های داستانی.md
> +# انسان‌ها
```suggestion

# کتاب های داستانی
## انسان‌ها
```

2024-09-17 19:14 UTC, HosnaSltn reviewed
ok

2024-09-17 19:14 UTC, HosnaSltn commented on docs/کلاب‌ها/بوک کلاب/کتاب‌های داستانی.md
> +🔹  **خلاصه:** وقتی ریاضیدانی بزرگترین مسئله‌ی حل نشده‌ی ریاضی را اثبات می‌کند، موجودی فضایی مأمور می‌شود بدن او را تسخیر کرده و تمامی آثار آن را پاک کند تا انسان‌ها که در دیدش موجوداتی منفور هستند از
```suggestion

```

2024-09-18 04:28 UTC, AminMasoudi approved these changes
Nice job

2024-09-18 04:28 UTC, AminMasoudi commented on docs/کلاب‌ها/بوک کلاب/index.md
> +![image]()
i've assume that You've forgotten to upload the image of the club.

2024-09-19 12:49 UTC, merged